default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-added-large-files
        args: ["--maxkb=100"]
        stages: [commit]
  # - repo: local
  #   hooks:
  #     - id: commit-message-style
  #       name: commit-message-style
  #       language: python
  #       stages: [commit-msg]
  #       entry: hooks/enforce_commit_message_style.py
