name: Git Checks
# Don't forget to write `git rebase -i --autosquash master` before merging
on: [pull_request]

jobs:
  block-fixup:
    # if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
    - name: Block Fixup Commit Merge
      uses: 13rac1/block-fixup-merge-action@v2.0.0
