name: pre-commit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  checks: write
  contents: write

jobs:
  format-code:
    name: Format code
    runs-on: ubuntu-latest
    # needs: [check-commit-message]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: isort/isort-action@master
        with:
          isortVersion: 5.10.1
          configuration: "--profile black"
      - uses: psf/black@stable
        with:
          options: ""
          src: "."
          version: "21.12b0"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated change"
          commit_options: --fixup ${{ github.head_ref }}
      - run: echo "Formatted the code"

  test-code:
    name: Test code
    runs-on: ubuntu-latest
    # needs: [check-commit-message]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests with pytest
        run: pytest
